In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [8]:
# see data type
print(arr.dtype)

# shape of array
print(arr.shape)

# create 2d array
arr_2d = np.array([[1,2,3], [4,5,6]])
print(arr_2d.shape)

int64
(5,)
(2, 3)


In [17]:
# create arr in buit in method


arr1 = np.zeros(3, dtype="int64") # 2d ((3,3))
print(arr1)

arr2 = np.ones(5)
print(arr2)

arr3 = np.full((2,2),7) #(2,7)
print(arr3)

arr4 = np.eye(3)
print(arr4)

arr5 = np.arange(1,10,2)# create arr in range (start, end, distance)
print(arr5)

arr6 = np.linspace(1, 100, 20)# rendomly create arr of 20 in betw 1 to 100 number
print(arr6)

[0 0 0]
[1. 1. 1. 1. 1.]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9]
[  1.           6.21052632  11.42105263  16.63157895  21.84210526
  27.05263158  32.26315789  37.47368421  42.68421053  47.89473684
  53.10526316  58.31578947  63.52631579  68.73684211  73.94736842
  79.15789474  84.36842105  89.57894737  94.78947368 100.        ]


In [22]:
# properties

arr = np.array([[1,2,3,5,4,6,7], [1,2,3,5,4,6,7]])

print(arr.shape) # shape in m x n  raw and column

print(arr.size) # size of arr 7

print(arr.dtype) # arr data type int64

print(arr.ndim)# arra dimenssion 1d

float_arr = arr.astype(np.float64)# change data type \\ int to float
print(float_arr, type(float_arr))

(2, 7)
14
int64
2
[[1. 2. 3. 5. 4. 6. 7.]
 [1. 2. 3. 5. 4. 6. 7.]] <class 'numpy.ndarray'>


In [30]:
# opereation
arr = np.array([[1,2,3,5,4,6,7], [1,2,3,5,4,6,7]])

# 1. reshaping
print(arr.shape)

reshape = arr.reshape(7,2)
print(reshape)

#flatten (convert to 1d array)
flatten = arr.flatten()
print()
print(flatten)

#indexing
arr = np.array([1,2,3,5,4,6,7]) #for 1d
print()
print(arr[4])

arr = np.array([[1,2,3,5,4,6,7], [1,2,3,5,4,6,7]])# for 2d
print()
print(arr[1][1])# arr[raw][column]

# fancY indexing
arr = np.array([1,2,3,5,4,6,7])
index = [6,5,4]
print()
print(arr[index])

# boolean indexing or masking
arr = np.array([1,2,3,5,4,6,7])
print()
print(arr[arr%2 == 0])


#slicing (did not take extra memory)
arr = np.array([1,2,3,5,4,6,7])
  ##[start: end: step] / [  : end: step] / [start: end]
#sub_arr = arr.[start: end: step]
print()
print(arr[1:6:2])



(2, 7)
[[1 2]
 [3 5]
 [4 6]
 [7 1]
 [2 3]
 [5 4]
 [6 7]]

[1 2 3 5 4 6 7 1 2 3 5 4 6 7]

4

2

[7 6 4]

[2 4 6]
[2 5 6]
